{"name": "test_delete_user", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../db.json'", "trace": "self = <allure_test.TestUserCRUD object at 0x0000018EE88638C0>\n\n    @pytest.fixture(autouse=True)\n    def setup_and_teardown(self):\n        # Setup: create a unique user for each test\n        self.user_id = faker.uuid4()\n        self.user = User(self.user_id, faker.name(), faker.email())\n>       user_crud.create(self.user_id, self.user)\n\nallure_test.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi_test.py:79: in create\n    data = self.file_handler.read_data()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.JSONHandler object at 0x0000018EE8861D90>\n\n    def read_data(self):\n>       with open(self.filename, 'r') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../db.json'\n\napi_test.py:65: FileNotFoundError"}, "start": 1703511136764, "stop": 1703511136764, "uuid": "faa56c7c-f6a6-4ed9-9d84-8e4ee992a4e7", "historyId": "d914b6bb74a92fb867c4f7cb00a3163c", "testCaseId": "d914b6bb74a92fb867c4f7cb00a3163c", "fullName": "allure_test.TestUserCRUD#test_delete_user", "labels": [{"name": "story", "value": "Delete User"}, {"name": "feature", "value": "User Operations"}, {"name": "suite", "value": "allure_test"}, {"name": "subSuite", "value": "TestUserCRUD"}, {"name": "host", "value": "DESKTOP-4HQA4QS"}, {"name": "thread", "value": "24960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_test"}]}